[package]
name = "scrambler"
version = "0.1.0-alpha"
description = "Scramble generator for Rubik's cubes"
edition = "2021"

[[bin]]
name = "scrambler"
path = "src/scrambler.rs"

[dependencies]
clap = "2.33.3"
colored = "2.0.0"
rand = "0.8.3"

[profile.release]
lto = true
panic = 'abort'
