indent_style = "Block"
use_small_heuristics = "Max" # "Default"
binop_separator = "Front"
combine_control_expr = true
comment_width = 100 # 80
condense_wildcard_suffixes = false
control_brace_style = "AlwaysSameLine"
disable_all_formatting = false
error_on_line_overflow = false
error_on_unformatted = false
fn_args_layout = "Tall"
brace_style = "SameLineWhere"
empty_item_single_line = true
enum_discrim_align_threshold = 0
fn_single_line = false
where_single_line = false
force_explicit_abi = true
format_strings = false
format_macro_matchers = true # false
format_macro_bodies = true
hard_tabs = false
imports_indent = "Block"
imports_layout = "Mixed"
merge_imports = false
match_block_trailing_comma = true # false
max_width = 100
merge_derives = true
force_multiline_blocks = false
newline_style = "Unix" # "Auto"
normalize_comments = false
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
reorder_impl_items = true # false
report_todo = "Never"
report_fixme = "Never"
skip_children = false
space_after_colon = true
space_before_colon = false
struct_field_align_threshold = 0
spaces_around_ranges = false
struct_lit_single_line = true
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
use_field_init_shorthand = false
use_try_shorthand = false
format_code_in_doc_comments = true # false
wrap_comments = true # false
match_arm_blocks = true
overflow_delimited_expr = true # false
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
#required_version = "CARGO_PKG_VERSION"
hide_parse_errors = false
color = "Auto"
unstable_features = true # false
ignore = []
edition = "2018"
version = "One"
normalize_doc_attributes = false
